### PR TITLE
Bader AlSeiari's Pull Request

### PR DESCRIPTION
**Pull request by bader11678**
Efforts done and features added by Bader AlSeiari: 

- (USER STORY) implemented a fully functional favorites feature that works across the application. Created FavoritesManager.java for better handling of favorites. Created a ManageFavoritesUseCase.java file to encapsulate business logic for managing favorites. Created a FavoritesView.java to integrate with LocationsWindow.java, enabling the functionality to implement across all views inheriting from LocationsWindow.

- (EXTRA FUNCTIONALITY) Implemented a Dropdown feature where when pressed, will display up to 5 options of cities that are similarly named with whatever has been typed so far in the text box.

- Added test files (FavoritesManagerTest, FavoritesViewTest) to ensure robustness of the favorites feature. (Still a work in progress).

- (Necessary changes to other files) Refactored Location class to align with checkstyle standards and ensure compatibility with the favorites feature. Updated OpenWeatherApiService to handle location searches more effectively.

### CODE REVIEW

**Comment by DojimaRyu** [comment]
Seems good to me; this code works well and doesn't interfere with other functionality. If possible, you should add the favorites tab to the Mercator Map (Login functionality is too ambitious). 

Good work!

**Comment by AkramKlai** [comment]
This is a very nice feature and works well with everything else in our user stories. It also follows CA and SOLID principle. Nice job!

**Comment by rmobmina** [comment]
Great work, Bader! The favorites feature looks like a solid addition, and the dropdown for city suggestions is a nice extra touch. Creating separate files like FavoritesManager, ManageFavoritesUseCase, and FavoritesView helps keep everything organized, so good job on that. The refactoring of Location and updates to OpenWeatherApiService also seem to make the app more efficient and easier to use.

**Comment by arham-w17** [comment]
Amazing! Refactoring the code made it more readable and easy to understand. I approve this merge.

**Pull request merged**
