### PR TITLE
My Other Contributions (+ some cleaning up of code and checkstyles)

### PR DESCRIPTION
**Pull request by AkramKlai**
Other Major Contribution: I was also responsible for integrating the UI and view models through the dashboard. The dashboard uses a simple factory to generate a class that constructs the basic UI structure for the main use cases being used in all user stories (i.e. entering locations, fetching weather data, and adding favourites). I made sure it was segregated in mind of SOLID design principles and following CA (i.e. including a view for each user story and presenter which is NewDashboardUI that shows whichever view based on user input).

Other Contributions:
- Implementing the design patterns with LocationsWindow.java (simple factory)
- Segregated the UI implementation into distinct parts to adhere to CA
- Worked on implement the WeatherDataDTO and a class that generate instances of it using the weather data
- Helped Edison out with the MecatorDisplayApp specifically in displaying the weather details in a pop window
- Helped with other user stories (mainly trying to have their classes work with the presenters and view models).
- Overall cleaning up code (to follow SOLID) and fixing checkstyles

### CODE REVIEW

**Comment by bader11678** [comment]
•	Overall implementation is splendid. Code adheres to standard coding practices with proper indentation. NewDashBoardUI maintains a clear and logical flow. The changes to the UI in order to adhere to Clean architecture is well made. The usage of a factory pattern looks robust. I recognize that you made additional test cases for the NewDashBoardUI file but make sure you cover most edge cases if possible.

**Review by arham-w17 — APPROVED** [review]
I love how the code adheres to SOLID principles and Clean Architecture. Your use of the simple factory design pattern for LocationsWindow.java stands out as a strong example of creating modular, maintainable code. Additionally, your effort to segregate UI implementations into distinct parts (based on the respective user stories) made it easier for everyone to understand the code.  Great work with fixing the checkstyles issues.

**Review by rmobmina — APPROVED** [review]
Code changes show a strong understanding of Clean Architecture and design principles. The use of the simple factory pattern in **LocationsWindow.java** is a great touch for keeping the code modular and easy to extend. I also appreciate how you segregated the UI components to align with SOLID, making the project more maintainable and scalable. Integrating the dashboard with the presenters and view models demonstrates careful thought about keeping dependencies clear and focused.

**Review by bader11678 — APPROVED** [review]
• Overall implementation is splendid. Code adheres to standard coding practices with proper indentation. NewDashBoardUI maintains a clear and logical flow. The changes to the UI in order to adhere to Clean architecture is well made. The usage of a factory pattern looks robust. I recognize that you made additional test cases for the NewDashBoardUI file but make sure you cover most edge cases if possible.

**Pull request merged**
