### PR TITLE
Bader AlSeiari's significant code contribution

### PR DESCRIPTION
**Pull request by bader11678**
Pull Request demonstrating another significant code contribution which I made to the project:

ALL significant code contributions (not related to my current user story) includes:
- Implementing API Into Dashboard
- Implemented DropDownUI, as well as heavily refactored it and fixed issues to allow multi-word city names and trimmed unnecessary spaces for better user experience, where we couldn't do so originally.
- Added new test files for my user story as well as increased robustness for other test files (for example OpenWeatherApiServiceTest).
- Refactored Location class to ensure compatibility with my user story.
- refactored OpenWeatherApiService to handle location searches more affectively.
- Fixed a bug related to Mercator Map where the file location was not found due to incorrect usage of backslashes.
- Refactored Mercator Window so that the weather information window closes when Mercator Window closes.
- Implemented Back button in HistoricalWeatherComparisonView.java
- Implemented Visualization feature (part of rmobmina's user story) into ForecastHourlyView.java (part of arham-w17's user story)

**- Overall, I have tried my best to contribute to every user story in order to have a full understanding of how each one works, and how they relate to each other in terms of functioning.**

**Note: a little of what I wrote here has already been mentioned in the last pull request I made since I was not aware of the difference between the purposes of what each pull request wanted me to do based on the individual contribution template.**

### CODE REVIEW

**Comment by rmobmina** [comment]
Nice!

**Review by arham-w17 — APPROVED** [review]
The updates to the test files reflect a focused effort on enhancing test coverage and ensuring that the functionality of the project is robust. This is a great step toward making sure every angle is covered when it comes to user functionality and overall reliability. Deleting the outdated DashboardUI was a proactive and necessary step that contributes to maintaining a clean and manageable codebase. It also resolved issues affecting the pushes made by others, which was crucial for smoother collaboration.
Overall, great job addressing these critical areas. I fully approve this merge!!!

**Review by rmobmina — COMMENTED** [review]
It's a good thing you got 100% coverage for your user cases Bader! Nice code.

**Review by DojimaRyu — APPROVED** [review]
Bader, this seems to work, but you are committing an extremely large volume of code at the same time.
As we have tested the current package on yaoediso_stories, I caan say that the code works there but I need you to extensively test this on the main branch - if this breaks main, we should rollback immediately. Specifically, we should be examining the tests and if mockito works as expected, as the group previously faced errors while running visualization tests.

I approve this pull request, but cautiously so and recommend a high scrutiny of testing from both yourself and other group members.

**Review by AkramKlai — APPROVED** [review]
The code for DropdownUI.java is nicely implemented with some SOLID principles in mind (such as single responsibility) but could use some cleaning up and refactoring to follow other SOLID principles (such as open-closed) and to fix check styles. This code does not have any test coverage so one of the main things I'd recommend is to add some basic unit tests to ensure the functionality of the dropdown menu. As for CA, it fits with the basic control flow of the presenters and view models that uses it as a dependency.  Other parts you worked on seems fine but again could use some cleaning up and more testing to ensure full code coverage.

**Review by rmobmina — APPROVED** [review]
Nice work on all of these unit tests!

**Pull request merged**
