### PR TITLE
yaoediso_stories

### PR DESCRIPTION
**Pull request by DojimaRyu**
Added most completed tests, implemented Mercator Projection Algorithm & Map App

### CODE REVIEW

**Review by rmobmina — APPROVED** [review]
The MercatorMapView class has clear design with proper inheritance from MultipleLocationsWindow. I like how you used constants like OPTION_NAME. A more detailed Javadoc at both class and method levels is necessary to describe the expected behavior and parameter constraints clearly for future improvement.

**Comment by AkramKlai** [comment]
This follows Clean Architecture quite well, with some enhancements to previously existing classes. I like how much more organized and segregated everything is with SOLID design principles in mind. Adding more descriptive comments and fixing check style errors would be as a next step to further improve upon this.

**Review by AkramKlai — APPROVED** [review]
This follows Clean Architecture as opposed to DashBoardUI.java. I like how much more organized and segregated everything is with SOLID design principles in mind. Adding more descriptive comments and fixing check style errors would be as a next step to further improve upon this.

**Review by bader11678 — APPROVED** [review]
Looks good to me. Follows requirements as needed. The structure is clear and easy to understand. Double check that no errors are present although I doubt there are any.

**Review by arham-w17 — APPROVED** [review]
Looks really good to me! The code reflects a solid application of software design principles, particularly Clean Architecture. I appreciate how its structured and easy to understand.

**Pull request merged**
