### PR TITLE
Yaoediso stories

### PR DESCRIPTION
**Pull request by DojimaRyu**
Added Mercator Map interactivity and segregation into CA. 
This pull request should work perfectly since the last pull request came from this branch.

### CODE REVIEW

**Review by bader11678 — APPROVED** [review]
Works as intended

**Review by rmobmina — APPROVED** [review]
I have not much to say, I was part of making this work and I saw it with my own eyes, the map looks fantastic.

Screenshot 2024-12-01 at 17 51 50

**Review by arham-w17 — APPROVED** [review]
Looks good!!

**Review by AkramKlai — APPROVED** [review]
This implementation seems pretty great. Follows CA well and with SOLID design principles in mind. Great job!

**Pull request merged**
