### PR TITLE
Merging changes regarding my user story (ForecastDailyView.java)

### PR DESCRIPTION
**Pull request by AkramKlai**
My User Story: I was responsible for the user story of being able to see daily weather forecast details including maximum and minimum temperatures, precipitation sum, and wind speeds and dominant direction. I made a simple UI design that is accessible and user-friendly, featuring buttons to see each day of the forecast as well as allowing them to change the number of days to forecast. The use cases being used here are getting the forecast weather data and the location data (both making API calls from OpenWeatherApiService.java) and getting the view to open up on dashboard.

### CODE REVIEW

**Comment by arham-w17** [comment]
The UI looks amazing and easy to use!! Nice work

**Comment by bader11678** [comment]
BRILLIANT! I approve of this

**Comment by rmobmina** [comment]
This pull request implements the daily weather forecast feature, allowing users to view details like temperatures, precipitation, and wind speed/direction with a simple and accessible UI. While the functionality works, there are areas for improvement. Test coverage is minimal, so unit tests for API responses and UI navigation, along with integration tests, should be added. The UI currently mixes data-fetching logic with display functionality, which could be refactored to follow SOLID principles by introducing a controller class.

**Comment by DojimaRyu** [comment]
Thanks for the help earlier! Your UI is a bit small, but pretty smooth and updates correctly. 
I got pretty badly stuck on the Swing stuff, so any help is appreciated.
Otherwise, some of the functionality here is changed - although I tested that this works, we should really keep the changes made here in mind when wrapping up stuff in the future.

Good work!

**Review by DojimaRyu — APPROVED** [review]
To copy from my previous comment;

Thanks for the help earlier! Your UI is a bit small, but pretty smooth and updates correctly.
I got pretty badly stuck on the Swing stuff, so any help is appreciated.
Otherwise, some of the functionality here is changed - although I tested that this works, we should really keep the changes made here in mind when wrapping up stuff in the future.

Good work!

**Pull request merged**
